<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      Maybe you are a beginner or maybe already have a lil bit of knowledge about web development but struggling about
      what to do now, this situation is quite common in new devs..
    </p>
    <h2 id="starting-up"><a href="#starting-up">Starting Up</a></h2>
    <p>
      If you have choosen that you want to go with web development, then I think the best thing you can do is start
      learning <strong>HTML</strong>
      , it&#39;s a quite easier markup language with angle brackets
      <code class="inline-code-block">&lt;&gt;</code>
       and very easy syntax like this:
    </p>
    <div class="code-block  ">
      <CodeCopy>
        <pre><code
            class="language-html">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">></span></span>I am a Paragraph<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>I don&#39;t think that would really take more than a week to master in HTML, once it&#39;s done..</p>
    <p>
      you can countinue your learning journey with <strong>CSS</strong>
      , again a markup language with power to make things beautiful, maybe you have understood it is used to style our
      web page.
    </p>
    <p>Let&#39;s see it&#39;s syntax:</p>
    <div class="code-block  ">
      <CodeCopy>
        <pre><code
            class="language-css">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token selector">.item</span> <span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token property">color</span><span class="token punctuation">:</span> pink<span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token property">background-color</span><span class="token punctuation">:</span> white<span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      HTML, CSS plays a important role in web development, even you become master at web development, you will have to
      use these both at some parts of th web, i think you will be able to create atleast a good looking small web page
      by learning these two.
    </p>
    <h2 id="continuing-with-javascript"><a href="#continuing-with-javascript">Continuing with Javascript</a></h2>
    <p>
      But that&#39;s not the end there&#39;s alot to go, now you have to learn a programming language, you would be
      confused to know that html, css are not programming languages, they are markup langs, but the lang you have to
      learn is <strong>JavaScript</strong>
      .
    </p>
    <blockquote>
      <p>Without JavaScript, the life of a web dev is like a painting without colors..</p>
    </blockquote>
    <p>
      Once you will learn it, you will be not able to live without coding with it, It&#39;s a quite beginners friendly
      language so you will have fun learning it..
    </p>
    <p>
      the next thing you can probably do is <a href="https://nodejs.org/" rel="external">Install Node.js</a>
       in your computer and start making use of it..
    </p>
    <p>You can become familiar with commands like -</p>
    <div class="code-block  showLineNumber">
      <CodeCopy>
        <pre><code
            class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="line-number">1</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">node</span> <span class="token operator">&lt;</span>file<span class="token operator">></span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">2</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">npm</span> <span class="token function">install</span> <span class="token operator">&lt;</span>package<span class="token operator">></span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">3</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">npm</span> run <span class="token operator">&lt;</span>command<span class="token operator">></span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h2 id="the-next-big-step"><a href="#the-next-big-step">The next big Step</a></h2>
    <p>
      if you have came here, now it&#39;s time to be introduced to the real web development world, it&#39;s time to
      start with a web framework like <a href="https://svelte.dev" rel="external">Svelte</a>
      ,
      <a href="https://reactjs.org" rel="external">React</a>
      ,
      <a href="https://vuejs.org" rel="external">Vue</a>
      ,
      <a href="https://angular.io" rel="external">Angular</a>
       and many more..
    </p>
    <p>
      I think you can start with svelte because it&#39;s the most loved framework for web development, but you should
      start with ReactJS as a student&#39;s prospective.
    </p>
    <h2 id="starting-backend-development"><a href="#starting-backend-development">Starting Backend Development</a></h2>
    <blockquote>
      <p>oh, that far? amazing! let&#39;s go with backend development..</p>
    </blockquote>
    <p>
      I think now you would have an app working amazingly but now, with backend development you can make your app more
      accessible by using <strong>databases for data storing</strong>
      ,
      <strong>user authentication</strong>
      and much more things..
      <br />
      now, you should learn to use
      <a href="https://mongodb.com/" rel="external">MongoDB</a>
      or any SQL Database(if you choose sql databases you will have to maybe learn a new language named SQL also), I
      think it&#39;s best to go with NoSQL Databases at first for beginners, and you can have other options like
      <a href="https://firebase.com/" rel="external">Firebase</a>
      or
      <a href="https://supabase.com/" rel="external">SupaBase</a>
      with
      <strong>MongoDB</strong>
      in NoSQL Databases and
      <a href="https://www.mysql.com/" rel="external">MySQL</a>
      or
      <a href="https://www.postgresql.org/" rel="external">PostgreSQL</a>
       in SQL Databases, i don&#39;t recommend sql databases..
    </p>
    <p>
      Intergrate your backend database with backend softwares for web development like <a
        href="https://expressjs.com/"
        rel="external">
        Express
      </a>
      for Vanilla JS, or if you have choosed Svelte, you can go with
      <a href="https://kit.svelte.dev" rel="external">SvelteKit</a>
      , for React you can go with
      <a href="https://nextjs.org/" rel="external">NextJS</a>
      , and
      <a href="https://nuxtjs.org/" rel="external">Nuxt</a>
       for Vue, Angular and Astro don&#39;t need extra js with them.
    </p>
    <p>
      after learning all these, i don&#39;t think at that time you will need any guide to help you, you could decide
      youself what to do next!
    </p>
    <p>Bye! Happy Coding!</p>
  </article>
</Post>
