<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Profile from '$custom/profile.svelte';
</script>

<Post>
  <article slot="post_content">
    <Profile bio="Life is a Journey" />

    <h2 id="introduction"><a href="#introduction">Introduction</a></h2>
    <p>
      Hi, I&#39;m Harsh Agrawal, a 15-year-old full stack developer and student based in India. I have a passion for
      technology and have been coding for the past two years. I got interested in full stack development after trying my
      hand at app and game development, but I found that my true calling was in web development. I am now capable of
      handling web projects that match those of many college graduates and I am thrilled to be a part of this
      ever-evolving tech world.
    </p>
    <h2 id="my-journey"><a href="#my-journey">My journey</a></h2>
    <p>
      it&#39;s been two years since i am coding, the time passed by without letting me realize. i am thrilled to be part
      of the constantly evolving tech industry. It&#39;s a little bad to constantly change your tech stacks in full
      stack development, but the knowledge you get, and more better dev you become is worth it.
    </p>
    <h2 id="current-tech-stack"><a href="#current-tech-stack">Current Tech Stack</a></h2>
    <p>
      Right now, I&#39;m particularly interested in a tech stack that includes Pocketbase, Express, Svelte, and Node.js
      - otherwise known as PESN. Although Pocketbase is still in its early stages, I have high hopes for its potential
      as a database solution for smaller or production-level projects. And of course, when it comes to more established
      databases, I also have experience using MongoDB.
    </p>
    <h2 id="some-advice"><a href="#some-advice">Some Advice</a></h2>
    <p>
      It&#39;s common for new developers to feel discouraged or even quit when comparing themselves to others who may
      seem to be achieving success more quickly. However, it&#39;s important to remember that everyone has their own
      unique skills and journeys in the tech industry. Success in software development doesn&#39;t come overnight, and
      it&#39;s crucial to stay focused on your own goals and put in the hard work. Don&#39;t be discouraged by others
      success, as it&#39;s not a reflection of your own potential. Embrace your own strengths and pace, and have faith
      in the power of hard work and dedication to eventually achieve your goals. Whether it takes a little longer or
      not, what truly matters is that you keep pushing forward and never give up on your dreams.
    </p>
    <h2 id="bye-have-a-nice-day"><a href="#bye-have-a-nice-day">Bye! Have a nice day!</a></h2>
  </article>
</Post>
